men=int(input("Введи число, а я покажу, какой месяц ему соответствует: "))
if men>12:print("Такого месяца нет")
if men<1:print("Такого месяца нет")
if men==1:print("январь")
elif men==2:print("Февраль")
elif men==3:print("Март")
elif men==4:print("Апрель")
elif men==5:print("Май")
elif men==6:print("Июнь")
elif men==7:print("Июль")
elif men==8:print("Август")
elif men==9:print("Сентябрь")
elif men==10:print("Октябрь")
elif men==11:print("Ноябрь")
elif men==12:print("Декабрь")

